In [1]:
#import libraries
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('fake_news.csv', index_col = None)
df

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [5]:
#removing unwanted column
dataset = df.drop("Unnamed: 0", axis=1, errors='ignore')
dataset

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [12]:
#train test split
from sklearn.model_selection import train_test_split

X = dataset['text']
y = dataset['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=53
)

In [13]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(dataset['text'],y, test_size = 0.33, random_state = 53)

In [14]:
X_train

14    A new satellite was successfully launched into...
2     Researchers announced a breakthrough treatment...
8     Studies confirm EVs help reduce carbon emissio...
0     The government has introduced a new AI policy ...
4     Global markets reached an all-time high due to...
6     Government plans major reforms to improve educ...
12    New investments improve hospitals and healthca...
5     A viral article claims a man created a time ma...
13    False claims circulate about humans achieving ...
9     A fake report claims scientists created a real...
Name: text, dtype: object

In [15]:
X_test

3     Social media falsely claims that salt water ca...
7     Fake news spreads about a celebrity adopting h...
11    Conspiracy theories falsely link 5G technology...
10    Government introduces subsidies to support sma...
1     Multiple viral posts claim aliens were seen wa...
Name: text, dtype: object

In [16]:
y_train

14    REAL
2     REAL
8     REAL
0     REAL
4     REAL
6     REAL
12    REAL
5     FAKE
13    FAKE
9     FAKE
Name: label, dtype: object

In [17]:
y_test

3     FAKE
7     FAKE
11    FAKE
10    REAL
1     FAKE
Name: label, dtype: object

In [18]:
#Conversion of text to number(vectors) using CountVectorizer
count_vectorizer = CountVectorizer(stop_words = 'english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 72 stored elements and shape (10, 64)>
  Coords	Values
  (0, 38)	1
  (0, 51)	1
  (0, 57)	1
  (0, 32)	1
  (0, 39)	1
  (1, 50)	1
  (1, 3)	1
  (1, 6)	1
  (1, 59)	1
  (1, 63)	1
  (1, 56)	1
  (2, 55)	1
  (2, 11)	1
  (2, 16)	1
  (2, 22)	1
  (2, 46)	1
  (2, 7)	1
  (2, 15)	1
  (2, 54)	1
  (3, 38)	1
  (3, 20)	1
  (3, 29)	1
  (3, 2)	1
  (3, 41)	1
  (3, 5)	1
  :	:
  (6, 53)	1
  (7, 58)	1
  (7, 61)	1
  (7, 4)	1
  (7, 9)	1
  (7, 36)	1
  (7, 12)	1
  (7, 34)	1
  (7, 24)	1
  (8, 9)	1
  (8, 18)	1
  (8, 8)	1
  (8, 26)	1
  (8, 1)	1
  (8, 0)	1
  (8, 62)	1
  (8, 33)	1
  (9, 9)	1
  (9, 12)	1
  (9, 17)	1
  (9, 49)	1
  (9, 52)	1
  (9, 44)	1
  (9, 31)	1
  (9, 10)	1

In [19]:
dir(count_train)

['T',
 '__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_allow_nd',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_ascontainer',
 '_asfptype',
 '_asindices',
 '_binopt',
 '_broadcast_to',
 '_bsr_container',
 '_container',
 '_coo_container',
 '_csc_container',
 '_csr_container',
 '_deduped_data',
 '_dia_container',
 '_divide',
 '_divide_sparse',
 '_dok_container',
 '_format',
 '_get_array',
 '_get_arrayXarray',
 '_get_arrayXint',
 '_get_arrayXslice',
 '_get_columnXarray',
 '_get_index_dtype',
 '_get_int',
 '_get_intXarray',
 '_get_intXint',
 '_get_intXslice',
 '_get_slice',
 '_get_sliceXarray',
 '_get_sliceXint',
 '_get_sliceXslice',
 '_get_submatrix',
 '_getcol',
 '_getmaxprint',
 '_getnnz',
 '_getrow',
 '_imag',
 '_inequality',
 '_insert_many',
 '_lil_container',
 '_major_index_fancy',
 '_major_slice',
 '_matmul_dispatch',
 '_matmul_multivector',
 '_matmul_sparse',
 '_matmul_vector',
 '_maximum_minimum',
 '_min_or_max',
 '_min_or_max_axis',
 '_minor_index_fancy',
 '_minor_reduce',
 '_minor_slice',
 '_mul_scalar',
 '_prepare_indices',
 '_process_toarray_args',
 '_real',
 '_rmatmul_dispatch',
 '_rsub_dense',
 '_scalar_binopt',
 '_set_array',
 '_set_arrayXarray',
 '_set_arrayXarray_sparse',
 '_set_int',
 '_set_intXint',
 '_set_many',
 '_setdiag',
 '_shape',
 '_shape_as_2d',
 '_sub_dense',
 '_sub_sparse',
 '_swap',
 '_validate_indices',
 '_with_data',
 '_zero_many',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctanh',
 'argmax',
 'argmin',
 'asformat',
 'asfptype',
 'astype',
 'ceil',
 'check_format',
 'conj',
 'conjugate',
 'copy',
 'count_nonzero',
 'data',
 'deg2rad',
 'diagonal',
 'dot',
 'dtype',
 'eliminate_zeros',
 'expm1',
 'floor',
 'format',
 'getH',
 'get_shape',
 'getcol',
 'getformat',
 'getmaxprint',
 'getnnz',
 'getrow',
 'has_canonical_format',
 'has_sorted_indices',
 'imag',
 'indices',
 'indptr',
 'log1p',
 'max',
 'maximum',
 'maxprint',
 'mean',
 'min',
 'minimum',
 'multiply',
 'nanmax',
 'nanmin',
 'ndim',
 'nnz',
 'nonzero',
 'power',
 'prune',
 'rad2deg',
 'real',
 'reshape',
 'resize',
 'rint',
 'set_shape',
 'setdiag',
 'shape',
 'sign',
 'sin',
 'sinh',
 'size',
 'sort_indices',
 'sorted_indices',
 'sqrt',
 'sum',
 'sum_duplicates',
 'tan',
 'tanh',
 'toarray',
 'tobsr',
 'tocoo',
 'tocsc',
 'tocsr',
 'todense',
 'todia',
 'todok',
 'tolil',
 'trace',
 'transpose',
 'trunc']

In [20]:
len(count_vectorizer.get_feature_names_out())

64

In [21]:
print(count_train.toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1
  0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]

In [22]:
# model creation using passive aggressive classification algorithm 
clf = PassiveAggressiveClassifier(max_iter=1000, random_state=0,
tol=1e-3)
clf.fit(count_train,y_train) # passing count_train from countvectorizer
#predicting using count_test from countvectorizer
pred = clf.predict(count_test)
#Evaluating using accuracy,confusion matrix and classification report
score = metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" % score)
cm = metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])
print("\nConfusion matrix:\n",cm)
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print("\nClassification_report:\n",report)

accuracy: 0.800

Confusion matrix:
 [[3 1]
 [0 1]]

Classification_report:
               precision    recall  f1-score   support

        FAKE       1.00      0.75      0.86         4
        REAL       0.50      1.00      0.67         1

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5

In [23]:
#predictions
dataset['text'][1]

'Multiple viral posts claim aliens were seen walking in NYC streets last night.'

In [24]:
count_train[1]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (1, 64)>

In [25]:
count_vectorizer = CountVectorizer(stop_words='english')
count_train = count_vectorizer.fit_transform(X_train)

In [30]:
X_train[[2]]

2    Researchers announced a breakthrough treatment...
Name: text, dtype: object

In [31]:
clf.predict(count_train[[1]])

array(['REAL'], dtype='<U4')

In [29]:
clf.predict(count_train[[2]])

array(['REAL'], dtype='<U4')

In [33]:
#import libraries
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import metrics
import matplotlib.pyplot as plt

In [34]:
df = pd.read_csv('fake_news.csv', index_col = None)
df

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [35]:
#removing unwanted column
dataset = df.drop("Unnamed: 0", axis=1, errors='ignore')
dataset

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [36]:
#train test split
from sklearn.model_selection import train_test_split

X = dataset['text']
y = dataset['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=53
)

In [37]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(dataset['text'],y, test_size = 0.33, random_state = 53)

In [38]:
X_train

14    A new satellite was successfully launched into...
2     Researchers announced a breakthrough treatment...
8     Studies confirm EVs help reduce carbon emissio...
0     The government has introduced a new AI policy ...
4     Global markets reached an all-time high due to...
6     Government plans major reforms to improve educ...
12    New investments improve hospitals and healthca...
5     A viral article claims a man created a time ma...
13    False claims circulate about humans achieving ...
9     A fake report claims scientists created a real...
Name: text, dtype: object

In [39]:
X_test

3     Social media falsely claims that salt water ca...
7     Fake news spreads about a celebrity adopting h...
11    Conspiracy theories falsely link 5G technology...
10    Government introduces subsidies to support sma...
1     Multiple viral posts claim aliens were seen wa...
Name: text, dtype: object

In [40]:
y_train

14    REAL
2     REAL
8     REAL
0     REAL
4     REAL
6     REAL
12    REAL
5     FAKE
13    FAKE
9     FAKE
Name: label, dtype: object

In [41]:
y_test

3     FAKE
7     FAKE
11    FAKE
10    REAL
1     FAKE
Name: label, dtype: object

In [42]:
#Conversion of text to number(vectors) using CountVectorizer
count_vectorizer = CountVectorizer(stop_words = 'english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 72 stored elements and shape (10, 64)>
  Coords	Values
  (0, 38)	1
  (0, 51)	1
  (0, 57)	1
  (0, 32)	1
  (0, 39)	1
  (1, 50)	1
  (1, 3)	1
  (1, 6)	1
  (1, 59)	1
  (1, 63)	1
  (1, 56)	1
  (2, 55)	1
  (2, 11)	1
  (2, 16)	1
  (2, 22)	1
  (2, 46)	1
  (2, 7)	1
  (2, 15)	1
  (2, 54)	1
  (3, 38)	1
  (3, 20)	1
  (3, 29)	1
  (3, 2)	1
  (3, 41)	1
  (3, 5)	1
  :	:
  (6, 53)	1
  (7, 58)	1
  (7, 61)	1
  (7, 4)	1
  (7, 9)	1
  (7, 36)	1
  (7, 12)	1
  (7, 34)	1
  (7, 24)	1
  (8, 9)	1
  (8, 18)	1
  (8, 8)	1
  (8, 26)	1
  (8, 1)	1
  (8, 0)	1
  (8, 62)	1
  (8, 33)	1
  (9, 9)	1
  (9, 12)	1
  (9, 17)	1
  (9, 49)	1
  (9, 52)	1
  (9, 44)	1
  (9, 31)	1
  (9, 10)	1

In [44]:
# model creation using classification algorithm 
clf = DecisionTreeClassifier(criterion='entropy',max_depth=50,min_samples_split=10,min_samples_leaf=2,random_state=42)
clf.fit(count_train,y_train) # passing count_train from countvectorizer
#predicting using count_test from countvectorizer
pred = clf.predict(count_test)
#Evaluating using accuracy,confusion matrix and classification report
score = metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" % score)
cm = metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])
print("\nConfusion matrix:\n",cm)
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print("\nClassification_report:\n",report)

accuracy: 0.400

Confusion matrix:
 [[1 3]
 [0 1]]

Classification_report:
               precision    recall  f1-score   support

        FAKE       1.00      0.25      0.40         4
        REAL       0.25      1.00      0.40         1

    accuracy                           0.40         5
   macro avg       0.62      0.62      0.40         5
weighted avg       0.85      0.40      0.40         5

In [45]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [46]:
df = pd.read_csv('fake_news.csv', index_col = None)
df

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [47]:
#train test split
from sklearn.model_selection import train_test_split

X = dataset['text']
y = dataset['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=53
)

In [48]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(dataset['text'],y, test_size = 0.33, random_state = 53)

In [49]:
X_train

14    A new satellite was successfully launched into...
2     Researchers announced a breakthrough treatment...
8     Studies confirm EVs help reduce carbon emissio...
0     The government has introduced a new AI policy ...
4     Global markets reached an all-time high due to...
6     Government plans major reforms to improve educ...
12    New investments improve hospitals and healthca...
5     A viral article claims a man created a time ma...
13    False claims circulate about humans achieving ...
9     A fake report claims scientists created a real...
Name: text, dtype: object

In [50]:
X_test

3     Social media falsely claims that salt water ca...
7     Fake news spreads about a celebrity adopting h...
11    Conspiracy theories falsely link 5G technology...
10    Government introduces subsidies to support sma...
1     Multiple viral posts claim aliens were seen wa...
Name: text, dtype: object

In [51]:
y_train

14    REAL
2     REAL
8     REAL
0     REAL
4     REAL
6     REAL
12    REAL
5     FAKE
13    FAKE
9     FAKE
Name: label, dtype: object

In [52]:
y_test

3     FAKE
7     FAKE
11    FAKE
10    REAL
1     FAKE
Name: label, dtype: object

In [53]:
#Conversion of text to number(vectors) using CountVectorizer
count_vectorizer = CountVectorizer(stop_words = 'english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 72 stored elements and shape (10, 64)>
  Coords	Values
  (0, 38)	1
  (0, 51)	1
  (0, 57)	1
  (0, 32)	1
  (0, 39)	1
  (1, 50)	1
  (1, 3)	1
  (1, 6)	1
  (1, 59)	1
  (1, 63)	1
  (1, 56)	1
  (2, 55)	1
  (2, 11)	1
  (2, 16)	1
  (2, 22)	1
  (2, 46)	1
  (2, 7)	1
  (2, 15)	1
  (2, 54)	1
  (3, 38)	1
  (3, 20)	1
  (3, 29)	1
  (3, 2)	1
  (3, 41)	1
  (3, 5)	1
  :	:
  (6, 53)	1
  (7, 58)	1
  (7, 61)	1
  (7, 4)	1
  (7, 9)	1
  (7, 36)	1
  (7, 12)	1
  (7, 34)	1
  (7, 24)	1
  (8, 9)	1
  (8, 18)	1
  (8, 8)	1
  (8, 26)	1
  (8, 1)	1
  (8, 0)	1
  (8, 62)	1
  (8, 33)	1
  (9, 9)	1
  (9, 12)	1
  (9, 17)	1
  (9, 49)	1
  (9, 52)	1
  (9, 44)	1
  (9, 31)	1
  (9, 10)	1

In [54]:
# model creation using classification algorithm 
clf = LogisticRegression(max_iter=1000, random_state=42)
clf.fit(count_train,y_train) # passing count_train from countvectorizer
#predicting using count_test from countvectorizer
pred = clf.predict(count_test)
#Evaluating using accuracy,confusion matrix and classification report
score = metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" % score)
cm = metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])
print("\nConfusion matrix:\n",cm)
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print("\nClassification_report:\n",report)

accuracy: 0.200

Confusion matrix:
 [[0 4]
 [0 1]]

Classification_report:
               precision    recall  f1-score   support

        FAKE       0.00      0.00      0.00         4
        REAL       0.20      1.00      0.33         1

    accuracy                           0.20         5
   macro avg       0.10      0.50      0.17         5
weighted avg       0.04      0.20      0.07         5

C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [56]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import  KNeighborsClassifier
from sklearn import metrics
import matplotlib.pyplot as plt

In [57]:
df = pd.read_csv('fake_news.csv', index_col = None)
df

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [58]:
#removing unwanted column
dataset = df.drop("Unnamed: 0", axis=1, errors='ignore')
dataset

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [59]:
#train test split
from sklearn.model_selection import train_test_split

X = dataset['text']
y = dataset['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=53
)

In [60]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(dataset['text'],y, test_size = 0.33, random_state = 53)

In [61]:
X_train

14    A new satellite was successfully launched into...
2     Researchers announced a breakthrough treatment...
8     Studies confirm EVs help reduce carbon emissio...
0     The government has introduced a new AI policy ...
4     Global markets reached an all-time high due to...
6     Government plans major reforms to improve educ...
12    New investments improve hospitals and healthca...
5     A viral article claims a man created a time ma...
13    False claims circulate about humans achieving ...
9     A fake report claims scientists created a real...
Name: text, dtype: object

In [62]:
X_test

3     Social media falsely claims that salt water ca...
7     Fake news spreads about a celebrity adopting h...
11    Conspiracy theories falsely link 5G technology...
10    Government introduces subsidies to support sma...
1     Multiple viral posts claim aliens were seen wa...
Name: text, dtype: object

In [63]:
y_train

14    REAL
2     REAL
8     REAL
0     REAL
4     REAL
6     REAL
12    REAL
5     FAKE
13    FAKE
9     FAKE
Name: label, dtype: object

In [64]:
y_test

3     FAKE
7     FAKE
11    FAKE
10    REAL
1     FAKE
Name: label, dtype: object

In [65]:
#Conversion of text to number(vectors) using CountVectorizer
count_vectorizer = CountVectorizer(stop_words = 'english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 72 stored elements and shape (10, 64)>
  Coords	Values
  (0, 38)	1
  (0, 51)	1
  (0, 57)	1
  (0, 32)	1
  (0, 39)	1
  (1, 50)	1
  (1, 3)	1
  (1, 6)	1
  (1, 59)	1
  (1, 63)	1
  (1, 56)	1
  (2, 55)	1
  (2, 11)	1
  (2, 16)	1
  (2, 22)	1
  (2, 46)	1
  (2, 7)	1
  (2, 15)	1
  (2, 54)	1
  (3, 38)	1
  (3, 20)	1
  (3, 29)	1
  (3, 2)	1
  (3, 41)	1
  (3, 5)	1
  :	:
  (6, 53)	1
  (7, 58)	1
  (7, 61)	1
  (7, 4)	1
  (7, 9)	1
  (7, 36)	1
  (7, 12)	1
  (7, 34)	1
  (7, 24)	1
  (8, 9)	1
  (8, 18)	1
  (8, 8)	1
  (8, 26)	1
  (8, 1)	1
  (8, 0)	1
  (8, 62)	1
  (8, 33)	1
  (9, 9)	1
  (9, 12)	1
  (9, 17)	1
  (9, 49)	1
  (9, 52)	1
  (9, 44)	1
  (9, 31)	1
  (9, 10)	1

In [67]:
# model creation using classification algorithm 
clf = KNeighborsClassifier(n_neighbors=3,metric = 'minkowski', p = 2)
clf.fit(count_train,y_train) # passing count_train from countvectorizer
#predicting using count_test from countvectorizer
pred = clf.predict(count_test)
#Evaluating using accuracy,confusion matrix and classification report
score = metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" % score)
cm = metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])
print("\nConfusion matrix:\n",cm)
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print("\nClassification_report:\n",report)

accuracy: 0.200

Confusion matrix:
 [[0 4]
 [0 1]]

Classification_report:
               precision    recall  f1-score   support

        FAKE       0.00      0.00      0.00         4
        REAL       0.20      1.00      0.33         1

    accuracy                           0.20         5
   macro avg       0.10      0.50      0.17         5
weighted avg       0.04      0.20      0.07         5

C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('fake_news.csv', index_col = None)
df

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [3]:
#removing unwanted column
dataset = df.drop("Unnamed: 0", axis=1, errors='ignore')
dataset

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [4]:
#train test split
from sklearn.model_selection import train_test_split

X = dataset['text']
y = dataset['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=53
)

In [5]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(dataset['text'],y, test_size = 0.33, random_state = 53)

In [6]:
X_train

14    A new satellite was successfully launched into...
2     Researchers announced a breakthrough treatment...
8     Studies confirm EVs help reduce carbon emissio...
0     The government has introduced a new AI policy ...
4     Global markets reached an all-time high due to...
6     Government plans major reforms to improve educ...
12    New investments improve hospitals and healthca...
5     A viral article claims a man created a time ma...
13    False claims circulate about humans achieving ...
9     A fake report claims scientists created a real...
Name: text, dtype: object

In [7]:
X_test

3     Social media falsely claims that salt water ca...
7     Fake news spreads about a celebrity adopting h...
11    Conspiracy theories falsely link 5G technology...
10    Government introduces subsidies to support sma...
1     Multiple viral posts claim aliens were seen wa...
Name: text, dtype: object

In [9]:
y_train

14    REAL
2     REAL
8     REAL
0     REAL
4     REAL
6     REAL
12    REAL
5     FAKE
13    FAKE
9     FAKE
Name: label, dtype: object

In [10]:
y_test

3     FAKE
7     FAKE
11    FAKE
10    REAL
1     FAKE
Name: label, dtype: object

In [11]:
#Conversion of text to number(vectors) using CountVectorizer
count_vectorizer = CountVectorizer(stop_words = 'english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 72 stored elements and shape (10, 64)>
  Coords	Values
  (0, 38)	1
  (0, 51)	1
  (0, 57)	1
  (0, 32)	1
  (0, 39)	1
  (1, 50)	1
  (1, 3)	1
  (1, 6)	1
  (1, 59)	1
  (1, 63)	1
  (1, 56)	1
  (2, 55)	1
  (2, 11)	1
  (2, 16)	1
  (2, 22)	1
  (2, 46)	1
  (2, 7)	1
  (2, 15)	1
  (2, 54)	1
  (3, 38)	1
  (3, 20)	1
  (3, 29)	1
  (3, 2)	1
  (3, 41)	1
  (3, 5)	1
  :	:
  (6, 53)	1
  (7, 58)	1
  (7, 61)	1
  (7, 4)	1
  (7, 9)	1
  (7, 36)	1
  (7, 12)	1
  (7, 34)	1
  (7, 24)	1
  (8, 9)	1
  (8, 18)	1
  (8, 8)	1
  (8, 26)	1
  (8, 1)	1
  (8, 0)	1
  (8, 62)	1
  (8, 33)	1
  (9, 9)	1
  (9, 12)	1
  (9, 17)	1
  (9, 49)	1
  (9, 52)	1
  (9, 44)	1
  (9, 31)	1
  (9, 10)	1

In [13]:
dir(count_train)

['T',
 '__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_allow_nd',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_ascontainer',
 '_asfptype',
 '_asindices',
 '_binopt',
 '_broadcast_to',
 '_bsr_container',
 '_container',
 '_coo_container',
 '_csc_container',
 '_csr_container',
 '_deduped_data',
 '_dia_container',
 '_divide',
 '_divide_sparse',
 '_dok_container',
 '_format',
 '_get_array',
 '_get_arrayXarray',
 '_get_arrayXint',
 '_get_arrayXslice',
 '_get_columnXarray',
 '_get_index_dtype',
 '_get_int',
 '_get_intXarray',
 '_get_intXint',
 '_get_intXslice',
 '_get_slice',
 '_get_sliceXarray',
 '_get_sliceXint',
 '_get_sliceXslice',
 '_get_submatrix',
 '_getcol',
 '_getmaxprint',
 '_getnnz',
 '_getrow',
 '_imag',
 '_inequality',
 '_insert_many',
 '_lil_container',
 '_major_index_fancy',
 '_major_slice',
 '_matmul_dispatch',
 '_matmul_multivector',
 '_matmul_sparse',
 '_matmul_vector',
 '_maximum_minimum',
 '_min_or_max',
 '_min_or_max_axis',
 '_minor_index_fancy',
 '_minor_reduce',
 '_minor_slice',
 '_mul_scalar',
 '_prepare_indices',
 '_process_toarray_args',
 '_real',
 '_rmatmul_dispatch',
 '_rsub_dense',
 '_scalar_binopt',
 '_set_array',
 '_set_arrayXarray',
 '_set_arrayXarray_sparse',
 '_set_int',
 '_set_intXint',
 '_set_many',
 '_setdiag',
 '_shape',
 '_shape_as_2d',
 '_sub_dense',
 '_sub_sparse',
 '_swap',
 '_validate_indices',
 '_with_data',
 '_zero_many',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctanh',
 'argmax',
 'argmin',
 'asformat',
 'asfptype',
 'astype',
 'ceil',
 'check_format',
 'conj',
 'conjugate',
 'copy',
 'count_nonzero',
 'data',
 'deg2rad',
 'diagonal',
 'dot',
 'dtype',
 'eliminate_zeros',
 'expm1',
 'floor',
 'format',
 'getH',
 'get_shape',
 'getcol',
 'getformat',
 'getmaxprint',
 'getnnz',
 'getrow',
 'has_canonical_format',
 'has_sorted_indices',
 'imag',
 'indices',
 'indptr',
 'log1p',
 'max',
 'maximum',
 'maxprint',
 'mean',
 'min',
 'minimum',
 'multiply',
 'nanmax',
 'nanmin',
 'ndim',
 'nnz',
 'nonzero',
 'power',
 'prune',
 'rad2deg',
 'real',
 'reshape',
 'resize',
 'rint',
 'set_shape',
 'setdiag',
 'shape',
 'sign',
 'sin',
 'sinh',
 'size',
 'sort_indices',
 'sorted_indices',
 'sqrt',
 'sum',
 'sum_duplicates',
 'tan',
 'tanh',
 'toarray',
 'tobsr',
 'tocoo',
 'tocsc',
 'tocsr',
 'todense',
 'todia',
 'todok',
 'tolil',
 'trace',
 'transpose',
 'trunc']

In [14]:
len(count_vectorizer.get_feature_names_out())

64

In [15]:
print(count_train.toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1
  0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]

In [16]:
# model creation using classification algorithm 
clf = RandomForestClassifier(n_estimators=100,max_features='sqrt',random_state=42)
clf.fit(count_train,y_train) # passing count_train from countvectorizer
#predicting using count_test from countvectorizer
pred = clf.predict(count_test)
#Evaluating using accuracy,confusion matrix and classification report
score = metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" % score)
cm = metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])
print("\nConfusion matrix:\n",cm)
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print("\nClassification_report:\n",report)

accuracy: 0.200

Confusion matrix:
 [[0 4]
 [0 1]]

Classification_report:
               precision    recall  f1-score   support

        FAKE       0.00      0.00      0.00         4
        REAL       0.20      1.00      0.33         1

    accuracy                           0.20         5
   macro avg       0.10      0.50      0.17         5
weighted avg       0.04      0.20      0.07         5

C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [17]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer,HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('fake_news.csv', index_col = None)
df

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [19]:
#removing unwanted column
dataset = df.drop("Unnamed: 0", axis=1, errors='ignore')
dataset

,id,title,text,label
0,1,Breaking: Government launches new AI policy,The government has introduced a new AI policy ...,REAL
1,2,Aliens landed in New York City,Multiple viral posts claim aliens were seen wa...,FAKE
2,3,Scientists discover cure for rare disease,Researchers announced a breakthrough treatment...,REAL
3,4,Drinking salt water cures COVID-19,Social media falsely claims that salt water ca...,FAKE
4,5,Stock market hits record high,Global markets reached an all-time high due to...,REAL
5,6,Man builds time machine in garage,A viral article claims a man created a time ma...,FAKE
6,7,New education policy announced,Government plans major reforms to improve educ...,REAL
7,8,Celebrity adopts 200 children,Fake news spreads about a celebrity adopting h...,FAKE
8,9,Electric vehicles reduce pollution,Studies confirm EVs help reduce carbon emissio...,REAL
9,10,Invisible cloak becomes reality,A fake report claims scientists created a real...,FAKE
10,11,Farmers benefit from new subsidy scheme,Government introduces subsidies to support sma...,REAL
11,12,5G towers spread viruses,Conspiracy theories falsely link 5G technology...,FAKE
12,13,Healthcare system upgraded nationwide,New investments improve hospitals and healthca...,REAL
13,14,Humans can live up to 200 years now,False claims circulate about humans achieving ...,FAKE
14,15,Space mission successfully launched,A new satellite was successfully launched into...,REAL

In [20]:
#train test split
from sklearn.model_selection import train_test_split

X = dataset['text']
y = dataset['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=53
)

In [21]:
#train test split
X_train,X_test,y_train,y_test = train_test_split(dataset['text'],y, test_size = 0.33, random_state = 53)

In [22]:
X_train

14    A new satellite was successfully launched into...
2     Researchers announced a breakthrough treatment...
8     Studies confirm EVs help reduce carbon emissio...
0     The government has introduced a new AI policy ...
4     Global markets reached an all-time high due to...
6     Government plans major reforms to improve educ...
12    New investments improve hospitals and healthca...
5     A viral article claims a man created a time ma...
13    False claims circulate about humans achieving ...
9     A fake report claims scientists created a real...
Name: text, dtype: object

In [23]:
X_test

3     Social media falsely claims that salt water ca...
7     Fake news spreads about a celebrity adopting h...
11    Conspiracy theories falsely link 5G technology...
10    Government introduces subsidies to support sma...
1     Multiple viral posts claim aliens were seen wa...
Name: text, dtype: object

In [24]:
y_train

14    REAL
2     REAL
8     REAL
0     REAL
4     REAL
6     REAL
12    REAL
5     FAKE
13    FAKE
9     FAKE
Name: label, dtype: object

In [25]:
y_test

3     FAKE
7     FAKE
11    FAKE
10    REAL
1     FAKE
Name: label, dtype: object

In [26]:
#Conversion of text to number(vectors) using CountVectorizer
count_vectorizer = CountVectorizer(stop_words = 'english')
count_train = count_vectorizer.fit_transform(X_train)
print(count_train)
count_test = count_vectorizer.transform(X_test)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 72 stored elements and shape (10, 64)>
  Coords	Values
  (0, 38)	1
  (0, 51)	1
  (0, 57)	1
  (0, 32)	1
  (0, 39)	1
  (1, 50)	1
  (1, 3)	1
  (1, 6)	1
  (1, 59)	1
  (1, 63)	1
  (1, 56)	1
  (2, 55)	1
  (2, 11)	1
  (2, 16)	1
  (2, 22)	1
  (2, 46)	1
  (2, 7)	1
  (2, 15)	1
  (2, 54)	1
  (3, 38)	1
  (3, 20)	1
  (3, 29)	1
  (3, 2)	1
  (3, 41)	1
  (3, 5)	1
  :	:
  (6, 53)	1
  (7, 58)	1
  (7, 61)	1
  (7, 4)	1
  (7, 9)	1
  (7, 36)	1
  (7, 12)	1
  (7, 34)	1
  (7, 24)	1
  (8, 9)	1
  (8, 18)	1
  (8, 8)	1
  (8, 26)	1
  (8, 1)	1
  (8, 0)	1
  (8, 62)	1
  (8, 33)	1
  (9, 9)	1
  (9, 12)	1
  (9, 17)	1
  (9, 49)	1
  (9, 52)	1
  (9, 44)	1
  (9, 31)	1
  (9, 10)	1

In [27]:
# model creation using classification algorithm 
clf = SVC(kernel='linear',C =10,gamma='auto')
clf.fit(count_train,y_train) # passing count_train from countvectorizer
#predicting using count_test from countvectorizer
pred = clf.predict(count_test)
#Evaluating using accuracy,confusion matrix and classification report
score = metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" % score)
cm = metrics.confusion_matrix(y_test,pred,labels=['FAKE','REAL'])
print("\nConfusion matrix:\n",cm)
from sklearn.metrics import classification_report
report=classification_report(y_test, pred)
print("\nClassification_report:\n",report)

accuracy: 0.200

Confusion matrix:
 [[0 4]
 [0 1]]

Classification_report:
               precision    recall  f1-score   support

        FAKE       0.00      0.00      0.00         4
        REAL       0.20      1.00      0.33         1

    accuracy                           0.20         5
   macro avg       0.10      0.50      0.17         5
weighted avg       0.04      0.20      0.07         5

C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\premchandar\anaconda3\envs\tf_env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])